
spring:
   profiles: peer2
server:
   port: 8769
eureka:
   instance:
#      hostname: peer2
      prefer-ip-address: true
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
      register-with-eureka: false
      fetch-registry: false